[package]
name = "clid"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Framework for building CLI→daemon execution hand-off systems"

[features]
default = ["local", "xdg", "env"]
local = ["clid-discovery/local"]
xdg = ["clid-discovery/xdg"]
env = ["clid-discovery/env"]
prefork = ["clid-daemon/prefork"]
check-bytes = ["clid-context/check-bytes"]

[dependencies]
clid-context = { path = "../clid-context" }
clid-discovery = { path = "../clid-discovery" }
clid-client = { path = "../clid-client" }
clid-daemon = { path = "../clid-daemon" }
